version: '3.8'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      - POSTGRES_PASSWORD=stat-db
      - POSTGRES_USER=stat-db
      - POSTGRES_DB=stat-db

  stats-server:
    build: ./stat/stat-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat-db
      - SPRING_DATASOURCE_USERNAME=stat-db
      - SPRING_DATASOURCE_PASSWORD=stat-db

  ewm-service:
    build: ./main-service
    container_name: evm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://ewm-stats-server:9090
